name: udemy_pengeluaran
version: 1.0.0+2
description: A new Flutter project.
environment: 
  sdk: '>=2.1.0 <3.0.0'
dependencies: 
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/images/waiting.png
  fonts: 
    - 
      family: OpenSans
      fonts: 
        - 
          asset: assets/font/OpenSans-Regular.ttf
        - 
          asset: assets/font/OpenSans-bold.ttf
          weight: 700
    - 
      family: Quicksand
      fonts: 
        - 
          asset: assets/font/Quicksand-Regular.ttf
        - 
          asset: assets/font/Quicksand-Bold.ttf
          weight: 700
  uses-material-design: true
